### PR TITLE
Enter api key / build with circle CI

### PR DESCRIPTION
**Pull request by zoff99**

### CODE REVIEW

**Comment by zoff99** [comment]
download apk file here:

https://circleci.com/gh/zoff99/NominatimGeocoderBackend/17#artifacts

capture_app_running

**Comment by ale5000-git** [comment]
@zoff99: Now that the other code has been merged could you please clean the pull request and leave only the "circle CI" part?

**Comment by ArchangeGabriel** [comment]
Now that #15 landed, this could be closed, right?

**Comment by ArchangeGabriel** [comment]
Oh, confused travis with circle, nevermind.

**Comment by zoff99** [comment]
@ale5000-git sure. will take a few days ...

**Comment by zoff99** [comment]
#17

**Pull request closed without merging**
