### PR TITLE
Use https

### LINKED ISSUE #8: Switch to HTTPS, retrieving location data securely
With all the effort this project puts in data privacy, choice and independence I don't understand how the requests are still made in plain text for anyone to sniff, log and modify.

Anyone can verify it by taking a cursory look. 

I wasn't expecting certificate pinning, but this is a bit silly. Even Google uses end-to-end TLS.

### PR DESCRIPTION
**Pull request by be-neth**
MapQuest and OSM APIs are accessible using HTTPS protocol.
Closes #8 .

Fix TAG string which can be at most 23 chars.

Note: Remember that you will still not be able to use Nominatim API if you do not have an API key. (See #4  )

### CODE REVIEW

**Comment by ArchangeGabriel** [comment]
For #4, a solution was proposed in #6, namely that the OSM one doesn’t require an API key. So it would just be a matter of changing the code to use the OSM one by default.

**Comment by ale5000-git** [comment]
@be-neth: Giving a fast look at the code I see "ssl", wouldn't be better switch to "tls"?

**Comment by be-neth** [comment]
Sorry I do not know enough about Java library to confirm but there is no javax.net.tls package.
I think (and I hope) that the underlying Https connection is using TLS protocol.

**Comment by ale5000-git** [comment]
@be-neth: I also don't know too much about this but I have found an example if it may help: http://www.programcreek.com/java-api-examples/javax.net.ssl.HttpsURLConnection

In the example there is: `SSLContext sc = SSLContext.getInstance("TLS");`

**Pull request merged**
